
project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - preface.qmd
    - 1-specifications.qmd
    - 2-points.qmd

website:
  navbar:
    tools:
    - icon: mastodon
      href: https://fosstodon.org/@opengeohub
    - icon: medium
      href: https://opengeohub.medium.com/
    - icon: twitter
      href: https://twitter.com/AI4SoilHealth
    - icon: github
      menu:
      - text: Source Code
        url:  https://github.com/AI4SoilHealth/SHDC4EU_manual
      - text: Report a Bug
        url:  https://github.com/AI4SoilHealth/SHDC4EU_manual/issues
    background: dark
    search: true
    logo: ./images/logo_ai4soilhealth_square.bw.short.png
    left:
      - text: "Project repositories"
        file: https://github.com/ai4soilhealth
      - text: "AI4SoilHealth project"
        file: https://ai4soilhealth.eu
  reader-mode: true
  repo-url: https://github.com/AI4SoilHealth/SHDC4EU_manual/
  repo-actions: [edit, issue]
  sidebar:
    style: "docked"
    contents:
      - section: "Soil Health Data Cube components"
        contents:
          - index.qmd
          - preface.qmd
          - 1-specifications.qmd
          - 2-points.qmd
      - section: "Data use tutorials"
        contents:
          - 3-shi.qmd
  page-footer:
    background: light
    left: "© 2024, OpenGeoHub foundation"
    right:
      - icon: github
        href: https://github.com/AI4SoilHealth/SHDC4EU_manual/
      - icon: mastodon
        href: https://fosstodon.org/@opengeohub
      - icon: twitter
        href: https://twitter.com/AI4SoilHealth
      - icon: linkedin
        href: https://www.linkedin.com/company/opengeohub-foundation/
      - icon: youtube
        href: https://www.youtube.com/c/OpenGeoHubFoundation
  title: "Soil Health Data Cube for Europe"
  twitter-card:
    image: "images/cover.png"
  open-graph:
    description: "Soil Health Data Cube for pan-EU (SHDC4EU) is compilation of pan-EU layers organized into a data cube and served through an API as analysis or decision ready data."

bibliography: references.bib

format:
  html:
    toc: true
    theme:
      light: flatly
      dark: solar
    mermaid:
      theme: dark
